### PR TITLE
aref error handling

### PR DESCRIPTION
**Pull request by kchanqvq**
This contains 2 commits that
1. fix bugs in aref error handling
2. reuse invalid-index condition and use existing abstract-arrays:invalid-array-index. I think invalid-index is a duplicate, but feel free to drop this commit if I missed something!

Thanks for your amazing work at bringing numerical computing to Common Lisp :)

### CODE REVIEW

**Comment by digikar99** [comment]
Thanks for the PR!

Some suggestions before the merge:

1. Replace `abstract-arrays::index` with `index` and instead edit the packages.lisp to [shadowing-]import-from abstract-arrays the symbol `index`? (Edit here: https://github.com/digikar99/dense-arrays/blob/2eb4e6d5e6e1f89cd083ab80fd8259423da94fd2/src/package.lisp#L69-L75)
2. Prefix the commit bug fix commit with `[fix] ...` and the removing invalid-index commit with `[int] ...`

**Comment by kchanqvq** [comment]
> 1. Replace `abstract-arrays::index` with `index` and instead edit the packages.lisp to [shadowing-]import-from abstract-arrays the symbol `index`

`abstract-arrays::index` is currently internal to `abstract-arrays`, so if we do this we'll have to change `abstract-arrays` to export it. Do we want this?

**Comment by digikar99** [comment]
`[shadowing-]import-from` works even if the symbols are internal (?)

**Comment by kchanqvq** [comment]
> `[shadowing-]import-from` works even if the symbols are internal (?)

Indeed! Whoa, there's always something to learn :) I'll implement these changes.

**Pull request merged**
